name: Build and Package Chrome Extension

on:
  push:
    tags:
      - 'v*'  # Triggers on tags like v1.0.0, v2.1.3, etc.

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '16'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install

      - name: Build extension
        run: yarn build

      - name: Rename dist folder
        run: mv dist rndmzr-chrome-extension

      - name: Zip extension
        run: zip -r rndmzr-chrome-extension.zip rndmzr-chrome-extension

      - name: Upload release asset to GitHub
        uses: softprops/action-gh-release@v2
        with:
          files: rndmzr-chrome-extension.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
